export const CATEGORIE_LIST_REQUEST = "CATEGORIE_LIST_REQUEST"
export const CATEGORIE_LIST_SUCCESS = "CATEGORIE_LIST_SUCCESS"
export const CATEGORIE_LIST_FAIL = "CATEGORIE_LIST_FAIL"

export const CATEGORIE_PRODUCTS_REQUEST = "CATEGORIE_PRODUCTS_REQUEST"
export const CATEGORIE_PRODUCTS_SUCCESS = "CATEGORIE_PRODUCTS_SUCCESS"
export const CATEGORIE_PRODUCTS_FAIL = "CATEGORIE_PRODUCTS_FAIL"

